// state
export const TEST = (process.env.NODE_ENV === 'test');

// test actions
export const TEST_DASHBOARD_ACTION = 'TEST_DASHBOARD_ACTION';
export const TEST_HOME_ACTION = 'TEST_HOME_ACTION';
export const TEST_MAIN_ACTION = 'TEST_MAIN_ACTION';

// authentication
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const VALIDATE_ACTION = 'VALIDATE_ACTION';

// dashboard page
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS';
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE';
export const GET_PROJECT_LOGS_SUCCESS = 'GET_PROJECT_LOGS_SUCCESS';
export const GET_PROJECT_LOGS_FAILURE = 'GET_PROJECT_LOGS_FAILURE';
export const GET_CONTAINERS_SUCCESS = 'GET_CONTAINERS_SUCCESS';
export const GET_CONTAINERS_FAILURE = 'GET_CONTAINERS_FAILURE';
