export const TEST_DASHBOARD_ACTION = 'TEST_DASHBOARD_ACTION';
export const TEST_LOGIN_ACTION = 'TEST_LOGIN_ACTION';
export const TEST_HOME_ACTION = 'TEST_HOME_ACTION';

// dashboard page
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS';
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE';
export const GET_PROJECT_LOGS_SUCCESS = 'GET_PROJECT_LOGS_SUCCESS';
export const GET_PROJECT_LOGS_FAILURE = 'GET_PROJECT_LOGS_FAILURE';
export const GET_CONTAINERS_SUCCESS = 'GET_CONTAINERS_SUCCESS';
export const GET_CONTAINERS_FAILURE = 'GET_CONTAINERS_FAILURE';
