name = "my_project"
url = "git@github.com:greatrepo/amazingproject.git"

[[profile]]
  name = "default"
  branch = "master"
  [profile.build]
    type = "dockerfile"
    buildfile = "Dockerfile"

[[profile]]
  name = "dev"
  branch = "dev"
  [profile.build]
    type = "docker-compose"
    buildfile = "dev/docker-compose.yml"

[[profile]]
  name = "staging"
  branch = "staging"
  [profile.build]
    type = "dockerfile"
    buildfile = "Dockerfile.staging"
