package main

import (
	"fmt"
	"os"

	"github.com/ubclaunchpad/inertia/cfg"
	hostcmd "github.com/ubclaunchpad/inertia/cmd/host"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	inertiacmd "github.com/ubclaunchpad/inertia/cmd/cmd"
	"github.com/ubclaunchpad/inertia/cmd/printutil"
)

// XCmd is the parent class for the 'inertia x' subcommands
type XCmd struct {
	*cobra.Command
	cfgPath string

	inertia *inertiacmd.Cmd
}

// AttachXCmds attaches 'x' subcommands to the given parent command
func AttachXCmds(inertia *inertiacmd.Cmd) {
	var remote = XCmd{inertia: inertia}
	remote.Command = &cobra.Command{
		Use:   "x",
		Short: "Experimental Inertia commands and features",
		Long: `Experimental Inertia commands, features, and utilities - some are intended
for development use only, and others are simply in-development features.`,
	}

	// add children
	remote.attachDocCmd()

	// add to parent
	inertia.AddCommand(remote.Command)
}

func (root *XCmd) attachDocCmd() {
	const (
		flagOutput = "output"
		flagFormat = "format"
	)
	var docs = &cobra.Command{
		Use:    "docs",
		Hidden: true,
		Short:  "List currently configured remotes",
		Long:   `Lists all currently configured remotes.`,
		Run: func(cmd *cobra.Command, args []string) {
			var output, _ = cmd.Flags().GetString(flagOutput)
			var format, _ = cmd.Flags().GetString(flagFormat)

			// create *full* Inertia tree, for sake of documentation
			hostcmd.AttachHostCmd(root.inertia, "${remote_name}", &cfg.Config{
				Remotes: map[string]*cfg.RemoteVPS{
					"${remote_name}": &cfg.RemoteVPS{Name: "${remote_name}"},
				},
			}, "", false)

			// set up file tree
			os.MkdirAll(output, os.ModePerm)

			// gen docs
			var err error
			switch format {
			case "man":
				err = doc.GenManTree(root.inertia.Command, &doc.GenManHeader{
					Title: "Inertia CLI",
					Source: fmt.Sprintf(
						"Generated by Inertia %s (https://github.com/ubclaunchpad/inertia)",
						root.Version),
					Manual: "https://inertia.ubclaunchpad.com",
				}, output)
			default:
				err = doc.GenMarkdownTree(root.inertia.Command, output)
			}
			if err != nil {
				printutil.Fatal(err.Error())
			}
			fmt.Printf("%s documentation generated in %s", format, output)
		},
	}
	docs.Flags().StringP(flagOutput, "o", "./inertia_cli_reference", "output file path")
	docs.Flags().StringP(flagFormat, "f", "md", "format to generate (md|man)")
	root.AddCommand(docs)
}
