package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/ubclaunchpad/inertia/cfg"
	"github.com/ubclaunchpad/inertia/cmd"

	inertiacmd "github.com/ubclaunchpad/inertia/cmd/cmd"
	hostcmd "github.com/ubclaunchpad/inertia/cmd/host"

	"github.com/ubclaunchpad/inertia/cmd/printutil"
)

// Version denotes the version of the binary
var Version string

func main() {
	var root = cmd.NewInertiaCmd(Version)
	if err := getDocgenCmd(root).Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}

func getDocgenCmd(root *inertiacmd.Cmd) *cobra.Command {
	const (
		flagOutput = "output"
		flagFormat = "format"
	)
	var docs = &cobra.Command{
		Use:    "docgen",
		Hidden: true,
		Short:  "Generate command reference for the Inertia CLI.",
		Run: func(cmd *cobra.Command, args []string) {
			var output, _ = cmd.Flags().GetString(flagOutput)
			var format, _ = cmd.Flags().GetString(flagFormat)

			// create *full* Inertia tree, for sake of documentation
			hostcmd.AttachHostCmd(root, "${remote_name}", &cfg.Config{
				Remotes: map[string]*cfg.RemoteVPS{
					"${remote_name}": &cfg.RemoteVPS{Name: "${remote_name}"},
				},
			}, "", false)

			// set up file tree
			os.MkdirAll(output, os.ModePerm)

			// gen docs
			var err error
			switch format {
			case "man":
				err = doc.GenManTree(root.Command, &doc.GenManHeader{
					Title: "Inertia CLI",
					Source: fmt.Sprintf(
						"Generated by Inertia %s (https://github.com/ubclaunchpad/inertia)",
						root.Version),
					Manual: "https://inertia.ubclaunchpad.com",
				}, output)
			default:
				err = doc.GenMarkdownTree(root.Command, output)
			}
			if err != nil {
				printutil.Fatal(err.Error())
			}

			fmt.Printf("%s documentation generated in %s", format, output)
		},
	}
	docs.Flags().StringP(flagOutput, "o", "./inertia_cli_reference", "output file path")
	docs.Flags().StringP(flagFormat, "f", "md", "format to generate (md|man)")
	return docs
}
