package crypto

import (
	jwt "github.com/dgrijalva/jwt-go"
)

// This file contains test assets

var (
	// TestPrivateKey is an example key for testing purposes
	TestPrivateKey = []byte("very_sekrit_key")

	// TestMasterToken is an example token for testing purposes. This is
	// generated by TestGenerateMasterToken, and is a master token.
	TestMasterToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2lkIjoiIiwidXNlciI6Im1hc3RlciIsImFkbWluIjp0cnVlLCJleHBpcnkiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9.tX9mIJOQ-S-_nJL6kjK8hAe5x5z6SpmDewDh5kUHOlk"

	// TestInertiaKeyPath the path to Inertia's test RSA key
	TestInertiaKeyPath = "../../../test/keys/id_rsa"
)

// GetFakeAPIKey is a helper function that implements jwt.keyFunc and returns
// the test private key
func GetFakeAPIKey(tok *jwt.Token) (interface{}, error) {
	return TestPrivateKey, nil
}
