name: Publish (release)

on:
  release:
    types: [ published ]

jobs:
  daemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with: { go-version: '1.14' }
    - name: Build release and publish daemon
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_key }}
        bash .scripts/release.sh
    - name: Publish CLI
      uses: softprops/action-gh-release@v1
      with:
        files: inertia.v*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
