name: Publish (latest)

on:
  push:
    branches: [ master ]

jobs:
  daemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build daemon
      run: make daemon-release RELEASE=latest

    - name: Publish to GitHub Container Registry
      run: |
        echo ${{ secrets.GH_PACKAGES_TOKEN }} | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin
        docker tag ubclaunchpad/inertiad:latest ghcr.io/ubclaunchpad/inertiad:latest
        docker push ghcr.io/ubclaunchpad/inertiad:latest
