name: Publish (latest)

on:
  push:
    branches: [ master ]

jobs:
  daemon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish daemon:latest
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_key }}
        make daemon-release RELEASE=latest
